In [7]:
import numpy as np
import pandas as pd

In [8]:
## Get the data from csv

path = './data/'

grid = pd.read_csv(path + 'f1_grid.csv')
grid.columns = ['position', 'time', 'driver', 'constructor', 'race']
results = pd.read_csv(path + 'f1_results.csv')
results.columns = ['position', 'laps', 'time', 'points', 'driver', 'constructor', 'race']

In [9]:
complete_merge = pd.merge(grid,results,how='outer', on=['driver', 'race'])

In [10]:
race_additions = complete_merge[complete_merge['position_x'].isna()]

##### For the drivers that can be found in the race but not in the grid; it just mean that they didn't do the qualy but did race. This could have happen for multiple reasons.

In [11]:
grid_additions = complete_merge[(complete_merge['position_y'].isna()) & (complete_merge['laps'].isna())]

In [12]:
len(race_additions) + len(grid_additions)

550

In [13]:
len(grid) - len(results)

492

In [14]:
grid_additions[grid_additions['race'] == '2003 Australian Grand Prix']

,position_x,time_x,driver,constructor_x,race,position_y,laps,time_y,points,constructor_y
731,1.0,1:27.173,Michael Schumacher,Ferrari,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
732,2.0,+0.245,Rubens Barrichello,Ferrari,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
733,3.0,+0.928,Juan Pablo Montoya,Williams,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
734,4.0,+1.101,Heinz-Harald Frentzen,Sauber,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
735,5.0,+1.115,Olivier Panis,Toyota,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
736,6.0,+1.247,Jacques Villeneuve,BAR,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
737,7.0,+1.291,Nick Heidfeld,Sauber,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
738,8.0,+1.509,Jenson Button,BAR,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
739,9.0,+1.657,Ralf Schumacher,Williams,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
740,10.0,+1.755,Fernando Alonso,Renault,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
741,11.0,+1.932,David Coulthard,McLaren,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
742,12.0,+1.963,Jarno Trulli,Renault,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
743,13.0,+2.171,Giancarlo Fisichella,Jordan,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
744,14.0,+2.194,Mark Webber,Jaguar,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
745,15.0,+2.297,Kimi Räikkönen,McLaren,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
746,16.0,+2.365,Cristiano da Matta,Toyota,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
747,17.0,+4.069,Ralph Firman,Jordan,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
748,18.0,+4.550,Antônio Pizzonia,Jaguar,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
749,19.0,NaN,Justin Wilson,Minardi,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN
750,20.0,NaN,Jos Verstappen,Minardi,2003 Australian Grand Prix,NaN,NaN,NaN,NaN,NaN

In [50]:
results_testing = results[results.race.apply(lambda x : x[:4]) == '2022']
print(results_testing.race.value_counts())
print(len(results_testing.race.value_counts()))

Series([], Name: race, dtype: int64)
0

In [ ]:
## 2001 : complete
## 2002 :  Less pilots from German Grand prix on
## 2003 : No pilots on 2003
## 2004 : 8 Races in 2004
## 2005 - : : Looks fine

In [62]:
grid_testing = grid[grid.race.apply(lambda x : x[:4]) == '2004']
print(grid_testing.race.value_counts())
print(len(grid_testing.race.value_counts()))

2004 Canadian Grand Prix         20
2004 Brazilian Grand Prix        20
2004 San Marino Grand Prix       20
2004 Belgian Grand Prix          20
2004 Chinese Grand Prix          20
2004 British Grand Prix          20
2004 Monaco Grand Prix           20
2004 Italian Grand Prix          20
2004 United States Grand Prix    20
2004 German Grand Prix           20
2004 French Grand Prix           20
2004 Hungarian Grand Prix        20
2004 European Grand Prix         20
2004 Australian Grand Prix       20
2004 Malaysian Grand Prix        20
2004 Bahrain Grand Prix          20
2004 Japanese Grand Prix         20
2004 Spanish Grand Prix          20
Name: race, dtype: int64
18

In [63]:
## So the inconsistency comes from not having years 2004 and 2003. I am going back to the other notebook to add them up.